### PR TITLE
WIP: Select translations by language

### PR DESCRIPTION
**Pull request by eatyourgreens**
- [x] Wires up the dropdown menu to select translations by language code.
- [x] Creates a new translation if none exist for the selected language code.
- [x] Lists existing translations, by language, in the project dashboard.
- [x] Loads in a translation if a language is specified when a resource component mounts.

### CODE REVIEW

**Comment by simoneduca** [comment]
Woohoo, good stuff! Taking a look now.

**Comment by eatyourgreens** [comment]
Rebased so that it doesn't include old commits from #19

**Comment by eatyourgreens** [comment]
I'm thinking that the top-level component should store the selected language code and pass it down to its children via props. The children can then load in a translation by listening for language changes in `componentWillRecieveProps`.

**Comment by simoneduca** [comment]
That makes sense. I take that's not included in this PR?

**Comment by eatyourgreens** [comment]
Should be. Have you had a chance to look at the code changes?

**Comment by eatyourgreens** [comment]
Testing it against your staging project: creating a new resource doesn't work yet (`resource.type` is undefined 😞) but selecting an existing translation by language code is working.

**Comment by simoneduca** [comment]
Ditto. I can see it here https://github.com/zooniverse/pandora/blob/9438f1ef383d787a37f1230ccd833df7c650a08e/src/ducks/resource.js#L124
Also `original` shouldn't be empty, should It? 
screen shot 2017-07-06 at 12 38 20

**Comment by eatyourgreens** [comment]
@simoneduca original isn't empty in your screenshot, it's an instance of `Resource` which you've expanded out in the debugger. The output from the log call is `'CREATE', original, translations, type, language`.

**Comment by simoneduca** [comment]
Oops, sorry! My bad.

**Comment by eatyourgreens** [comment]
608d0da fixes the resource type, but feels like a hack to me. I'm not comfortable with directly accessing underscored properties.

**Comment by simoneduca** [comment]
I'm not either.

**Comment by eatyourgreens** [comment]
I've deleted that commit and replaced with 0dc49af, which tries to get resource type from the URL instead.

**Comment by simoneduca** [comment]
Testing it as is for now, I'm observing some unexpected behaviour, I think.
I'm not sure we want to store `lang` in the `original`...
Also, I don't know why `createTranslation` can't find that `id`, as it seesm the correct one.
screen shot 2017-07-06 at 13 04 35

**Comment by eatyourgreens** [comment]
I'm not sure why it's making a PUT request, since this PR commented out the `save` call.

**Comment by simoneduca** [comment]
Sorry, I wasn't clear. I wanted to test the call, so I've uncommented it.

**Comment by eatyourgreens** [comment]
Maybe we should have this conversation on Slack, to avoid noise here, and use github comments to comment on changes we've commited?

**Comment by simoneduca** [comment]
To make the view a bit more terse, it might be an idea to show the dropdown options as checkboxes, where the existing translations are already checked? With that in place, we could think of not having an explicit list of languages.

**Comment by eatyourgreens** [comment]
Tidied up and squashed the merge commit.

**Comment by eatyourgreens** [comment]
I think the UI should be similar to translations.zooniverse.org: radio buttons for existing languages or type into a text box to select a new language.

**Comment by simoneduca** [comment]
I think this is ready to merge, once Travis is done. Are you happy?

**Comment by eatyourgreens** [comment]
Sounds good to me. 👍

**Pull request merged**
